sudo: required

language: generic

services:
  - docker

script:
  - docker build -t "${USERNAME}/${IMAGE}":latest .

deploy:
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push "${USERNAME}/${IMAGE}:latest"
    
