dist: trusty
group: travis_latest
language: generic

language: generic

cache:
  bundler: true
  directories:
    - $HOME/docker

services:
  - docker

before_install:
  # Load cached docker images
  - [[ -f $HOME/docker/nginx-with-certbot-in-docker.gz ]] && sh -c "zcat $HOME/docker/nginx-with-certbot-in-docker.gz | docker load"

before_script:
  - IFS='/' read -ra TMP <<< "$TRAVIS_REPO_SLUG"
  - if [ -z ${USERNAME+x} ]; then export "USERNAME=${TMP[0]}"; fi
  - if [ -z ${IMAGE+x} ];    then export "IMAGE=${TMP[1]}"; fi
  
  # Make sure that the base image is up-to date
  - docker pull "$(sed -n 's/FROM[ ]*\(.*\)/\1/p' 'Dockerfile')"

script:
  - docker build -t "${USERNAME}/${IMAGE}:latest" .

before_cache:
  # Save tagged docker images
  - >
    mkdir -p $HOME/docker && rm -rf $HOME/docker/* && sh -c "docker save ${USERNAME}/${IMAGE}:latest | gzip -2 > $HOME/docker/nginx-with-certbot-in-docker.gz"

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

deploy:
  skip_cleanup: true
  provider: script
  script: docker push "${USERNAME}/${IMAGE}:latest"
    
