#!/usr/bin/env bash

source "/env.sh"

###########################
echo Renew certificates ###
###########################

if [ -d $LETSENCRYPT_LIVE ]; then
    certbot renew --webroot -w /var/www/letsencrypt >> /var/log/cron.log 2>&1
    /usr/sbin/nginx -s reload                       >> /var/log/cron.log 2>&1
fi
